# Pull base image.
FROM ubuntu:14.04

# Add string.txt to /data
RUN mkdir src 
ADD rmi /src/rmi
ADD PingPong.java /src/PingPong.java 
ADD PingPongClient.java /src/PingPongClient.java 
ADD PingPongInterface.java /src/PingPongInterface.java 
ADD PingPongServer.java /src/PingPongServer.java 
ADD PingPongServerFactory.java /src/PingPongServerFactory.java 
